# Generated by Django 3.1 on 2020-08-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask_question',
            options={'verbose_name': 'Ask Question', 'verbose_name_plural': 'Ask Questions'},
        ),
        migrations.AlterModelOptions(
            name='conetest_problem',
            options={'verbose_name': 'Conntest Problem', 'verbose_name_plural': 'Contest Problems'},
        ),
    ]
