# Generated by Django 3.0.8 on 2020-07-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Problem', '0001_initial'),
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conetest_problems',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Problem.Problems'),
        ),
        migrations.AddField(
            model_name='ask_questions',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.Contests'),
        ),
    ]
