# Generated by Django 3.0.8 on 2020-07-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contest', '0002_auto_20200720_2350'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_questions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Users'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.Contests'),
        ),
        migrations.AlterUniqueTogether(
            name='conetest_problems',
            unique_together={('contest_id', 'problem_id')},
        ),
    ]
