# Generated by Django 5.2.3 on 2025-06-28 08:03

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contest', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rating', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Rating Status',
                'verbose_name_plural': 'Rating Status',
            },
        ),
        migrations.CreateModel(
            name='Rating_Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_change', models.IntegerField()),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
            options={
                'verbose_name': 'Rating Change',
                'verbose_name_plural': 'Rating Changes',
                'unique_together': {('contest_id', 'profile_id')},
            },
        ),
    ]
