# Generated by Django 3.1 on 2020-08-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating_change',
            options={'verbose_name': 'Rating Change', 'verbose_name_plural': 'Rating Changes'},
        ),
        migrations.AlterModelOptions(
            name='rating_status',
            options={'verbose_name': 'Rating Status', 'verbose_name_plural': 'Rating Status'},
        ),
    ]
