# Generated by Django 4.2.23 on 2025-06-15 19:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_status',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
