# Generated by Django 3.0.8 on 2020-07-20 17:50

import User.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('google_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('cur_rating', models.IntegerField()),
                ('have_profile_image', models.ImageField(upload_to=User.models.UploadToPathAndRename('upload\\profile_image'))),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institution.Institutions')),
            ],
        ),
    ]
