# Generated by Django 3.1 on 2020-08-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem_tag',
            options={'verbose_name': 'Problem Tag', 'verbose_name_plural': 'Problem Tags'},
        ),
    ]
