# Generated by Django 4.2.23 on 2025-06-15 19:16

import Problem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='expected_output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_producer',
            field=models.FileField(upload_to=Problem.models.UploadToPathAndRename('upload/output_producer')),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_validator',
            field=models.FileField(upload_to=Problem.models.UploadToPathAndRename('upload/output_validator')),
        ),
    ]
