# Generated by Django 3.1 on 2020-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cur_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
