# Generated by Django 4.2.23 on 2025-06-15 19:16

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20200821_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='have_profile_image',
            field=models.ImageField(null=True, upload_to=Profile.models.UploadToPathAndRename('upload/profile_image')),
        ),
    ]
