# Generated by Django 3.1 on 2020-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20200814_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
