# Generated by Django 3.0.8 on 2020-07-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Team', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='team_members',
            unique_together={('team_id', 'user_id')},
        ),
    ]
