# Generated by Django 5.2.3 on 2025-06-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contest', '0001_initial'),
        ('Problem', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('time_taken', models.DurationField()),
                ('memory_used', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(max_length=5)),
                ('compile_output', models.TextField(blank=True, null=True)),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Submission.language')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Problem.problem')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
    ]
