# Generated by Django 4.2.23 on 2025-06-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compile_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
