# Generated by Django 3.0.8 on 2020-07-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Users'),
        ),
    ]
